/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();
        Logincontinue = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Request_Account = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        Manager = new javax.swing.JRadioButton();
        Receptionist = new javax.swing.JRadioButton();
        Housekeeping = new javax.swing.JRadioButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        Welcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("Welcome To NEC Hotel Management System");
        Welcome.setAlignmentX(0.5F);

        Logincontinue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Logincontinue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logincontinue.setText("Please Login To Continue");

        jLabel4.setText("Password");

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        jLabel5.setText("Forgot Password ? Contact Manager");

        jLabel6.setText("New To NEC Hotel ?");

        Request_Account.setText("Request Account");
        Request_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Request_AccountActionPerformed(evt);
            }
        });

        jLabel7.setText("Select Your Role");

        Manager.setText("Manager");
        Manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerActionPerformed(evt);
            }
        });

        Receptionist.setText("Receptionist");
        Receptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceptionistActionPerformed(evt);
            }
        });

        Housekeeping.setText("Housekeeping");
        Housekeeping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HousekeepingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(Logincontinue, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Username)
                                    .addComponent(Password)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Request_Account))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Manager, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(Receptionist, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(Housekeeping)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Welcome)
                .addGap(18, 18, 18)
                .addComponent(Logincontinue)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Manager)
                    .addComponent(Receptionist)
                    .addComponent(Housekeeping))
                .addGap(18, 18, 18)
                .addComponent(Login)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Request_Account))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Request_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Request_AccountActionPerformed
        JFrame RequestANewAccountPopupMenu=new JFrame("Message");
        JOptionPane.showMessageDialog(RequestANewAccountPopupMenu,"Please contact your manager for a new account.", "Message",JOptionPane.ERROR_MESSAGE); 

    }//GEN-LAST:event_Request_AccountActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String username=Username.getText(); 
        char password1[]=Password.getPassword();
        String password=String.copyValueOf(password1);
        String role; 
        if(Manager.isSelected()){
            role="Manager"; 
        }
        else if(Receptionist.isSelected()){
            role="Receptionist"; 
        }
        else if(Housekeeping.isSelected()){
            role="Housekeeping"; 
        }
        else{
            role="";
        }
        
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;
        try {
            try {
                // Load the MySQL JDBC driver
                Class.forName("com.mysql.cj.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            // Establish the connection
            String url = "jdbc:mysql://localhost:3306/NEC_Hotel";
            String user = "root";
            String pass = "root";
            connection = DriverManager.getConnection(url, user, pass);
            // Create a statement
            statement = connection.createStatement();
            // Execute a query
            String query = "Select Username, Password, role from User where Username='"+username+"' and Password='"+password+"' and Role='"+ role +"';";
            System.out.println(query);
           
            try{
            resultSet =statement.executeQuery(query);
            if(resultSet.next()){
                String rolecheck=resultSet.getString("Role");
                System.out.println(rolecheck);
                if(null != rolecheck)
                    switch (rolecheck) {
                    case "Manager" -> {
                        ManagerDashboard managerDashboard=new ManagerDashboard();
                        managerDashboard.setVisible(true);
                        this.setVisible(false);
                    }
                    case "Receptionist" -> {
                        ReceptionistDashboard receptionistDashboard=new ReceptionistDashboard();
                        receptionistDashboard.setVisible(true);
                        this.setVisible(false);
                    }
                    case "Housekeeping" -> {
                        HousekeepingDashboard housekeepingDashboard=new HousekeepingDashboard();
                        housekeepingDashboard.setVisible(true);
                        this.setVisible(false);
                    }
                    default -> {
                    }
                    }
                      
            }
            else{
                JFrame DetailsDoNotMatchPopupMenu=new JFrame("Message");
                JOptionPane.showMessageDialog(DetailsDoNotMatchPopupMenu,"Opps! Details do not match.", "Message",JOptionPane.ERROR_MESSAGE); 
            }               
        }
            catch(Exception e){
                JFrame ServerIssePopupMenu=new JFrame("Message");
                JOptionPane.showMessageDialog(ServerIssePopupMenu,"Sever issue occured.", "Message",JOptionPane.ERROR_MESSAGE);      
            }
        }
        catch ( SQLException e) {
            JFrame ServerConnectionErrorPopupMenu=new JFrame("Message");
                JOptionPane.showMessageDialog(ServerConnectionErrorPopupMenu,"Can not connect server. Please try later.", "Message",JOptionPane.ERROR_MESSAGE);      
    
            e.printStackTrace();
        } finally {
            // Close connections and resources in the reverse order of creation
            try {
                if (resultSet != null) resultSet.close();
                if (statement != null) statement.close();
                if (connection != null) connection.close();
            }catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_LoginActionPerformed

        
    private void ManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerActionPerformed
        if(Manager.isSelected()){
            Receptionist.setSelected(false); 
            Housekeeping.setSelected(false);
        }
        else {
            Manager.setSelected(true);
        }
    }//GEN-LAST:event_ManagerActionPerformed

    private void ReceptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceptionistActionPerformed
        if(Receptionist.isSelected()){
            Manager.setSelected(false); 
            Housekeeping.setSelected(false);
        }
        else {
            Receptionist.setSelected(true);
        }
    }//GEN-LAST:event_ReceptionistActionPerformed

    private void HousekeepingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HousekeepingActionPerformed
        if(Housekeeping.isSelected()){
            Receptionist.setSelected(false); 
            Manager.setSelected(false);
        }
        else {
            Housekeeping.setSelected(true);
        }
    }//GEN-LAST:event_HousekeepingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Housekeeping;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Logincontinue;
    private javax.swing.JRadioButton Manager;
    private javax.swing.JPasswordField Password;
    private javax.swing.JRadioButton Receptionist;
    private javax.swing.JButton Request_Account;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
