/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

/**
 *
 * @author Admin
 */
public class ReceptionistDashboard extends javax.swing.JFrame {

    /**
     * Creates new form ReceptionistDashboard
     */
    public ReceptionistDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Room_Management = new javax.swing.JButton();
        Guest_Management = new javax.swing.JButton();
        Billing_And_Payments = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Daily_Report = new javax.swing.JButton();
        Booking_System = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To Your Dashboard");

        Room_Management.setText("Room Management");
        Room_Management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_ManagementActionPerformed(evt);
            }
        });

        Guest_Management.setText("Guest Management");
        Guest_Management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guest_ManagementActionPerformed(evt);
            }
        });

        Billing_And_Payments.setText("Billing and Payments");
        Billing_And_Payments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Billing_And_PaymentsActionPerformed(evt);
            }
        });

        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Daily_Report.setText("Daily Report");
        Daily_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Daily_ReportActionPerformed(evt);
            }
        });

        Booking_System.setText("Booking System");
        Booking_System.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Booking_SystemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Room_Management, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Billing_And_Payments, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(Guest_Management, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Daily_Report, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(Booking_System, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Room_Management)
                .addGap(18, 18, 18)
                .addComponent(Booking_System)
                .addGap(18, 18, 18)
                .addComponent(Guest_Management)
                .addGap(18, 18, 18)
                .addComponent(Billing_And_Payments)
                .addGap(18, 18, 18)
                .addComponent(Daily_Report)
                .addGap(18, 18, 18)
                .addComponent(Logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Room_ManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_ManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_ManagementActionPerformed

    private void Guest_ManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guest_ManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Guest_ManagementActionPerformed

    private void Billing_And_PaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Billing_And_PaymentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Billing_And_PaymentsActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Login login=new Login(); 
        login.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_LogoutActionPerformed

    private void Daily_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Daily_ReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Daily_ReportActionPerformed

    private void Booking_SystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Booking_SystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Booking_SystemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionistDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Billing_And_Payments;
    private javax.swing.JButton Booking_System;
    private javax.swing.JButton Daily_Report;
    private javax.swing.JButton Guest_Management;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Room_Management;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
